apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: "production"
  APP_PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # Chuỗi "supersecretpassword" đã được mã hóa base64
  DB_PASSWORD: "c3VwZXJzZWNyZXRwYXNzd29yZA=="
