events {
    worker_connections 1024;
}

http {
    proxy_cache_path /var/cache/nginx keys_zone=cdn_cache:10m max_size=1g;

    server {
        listen 80;

        location / {
            # Sử dụng DNS mặc định bên trong mạng Docker để phân giải động
            resolver 127.0.0.11 valid=30s;
            
            # Gán tên upstream vào một biến để ép Nginx chỉ phân giải khi có request thật truyền vào
            set $backend_servers "http://web-app-01:80";

            proxy_pass $backend_servers;
            proxy_cache cdn_cache;
            proxy_cache_valid 200 302 10m;
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}

