events {
    worker_connections 1024;
}

http {
    # Giả lập cấu hình Cache vùng đệm cho CDN
    proxy_cache_path /var/cache/nginx keys_zone=cdn_cache:10m max_size=1g;

    upstream backend_servers {
        server web-app-01:80;
        server web-app-02:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
            proxy_cache cdn_cache;
            proxy_cache_valid 200 302 10m;
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}

