events {}
http {
    server {
        listen 80;
        location / {
            # Gọi trực tiếp tên dịch vụ và cổng nội bộ của nó bên trong mạng Docker
            proxy_pass http://web-app:80; 
        }
    }
}

